import { createFileRoute } from "@tanstack/react-router";
import { toast } from "sonner";
import {
  ShieldCheck,
  Lock,
  FileText,
  Database,
  UserCheck,
  Trash2,
  Download,
  Eye,
  ScrollText,
} from "lucide-react";
import { PageHeader, StatCard, Card } from "@/components/ui/chai";

export const Route = createFileRoute("/app/trust")({
  head: () => ({ meta: [{ title: "Trust & Compliance — Chai" }] }),
  component: Trust,
});

const inventory = [
  { type: "Customer profiles", source: "CSV upload", classification: "Personal data", retention: "36 months" },
  { type: "Transactions", source: "CSV upload", classification: "Financial", retention: "84 months" },
  { type: "Support conversations", source: "Zendesk (OAuth)", classification: "Personal data", retention: "24 months" },
  { type: "Survey responses", source: "CSV upload", classification: "Personal data", retention: "24 months" },
  { type: "Health & risk scores", source: "Generated by Chai", classification: "Derived", retention: "Until deleted" },
];

const controls = [
  { icon: Lock, title: "Encryption", desc: "Data is encrypted in transit (TLS) and at rest (AES-256)." },
  { icon: UserCheck, title: "Role-based access", desc: "Only invited team members can view customer data, by role." },
  { icon: ScrollText, title: "Audit logs", desc: "Every access and export is recorded with who, what and when." },
  { icon: Eye, title: "AI transparency", desc: "Each score links to the exact factors that produced it." },
];

const auditLog = [
  { who: "you@northwind.co", action: "Viewed customer Acme Labs", when: "2 minutes ago" },
  { who: "system", action: "Synced 142 tickets from Zendesk", when: "4 minutes ago" },
  { who: "you@northwind.co", action: "Exported risk report (CSV)", when: "Yesterday" },
  { who: "casey@northwind.co", action: "Updated retention policy: Support data → 24 months", when: "3 days ago" },
];

const reports = [
  { name: "Compliance report", icon: ShieldCheck },
  { name: "Data inventory report", icon: Database },
  { name: "Audit report", icon: ScrollText },
  { name: "Privacy report", icon: FileText },
];

function Trust() {
  return (
    <div>
      <PageHeader
        title="Trust & Compliance Center"
        description="A GDPR-first view of exactly what data exists, where it came from, how it's used, and how it can be deleted — so you can upload customer data with confidence."
      >
        <span className="inline-flex items-center gap-1.5 rounded-full border border-success/20 bg-success/10 px-3 py-1 text-xs font-medium text-success">
          <ShieldCheck className="h-3.5 w-3.5" /> GDPR-ready
        </span>
      </PageHeader>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard label="Compliance health" value="92%" icon={ShieldCheck} tone="success" />
        <StatCard label="Encryption" value="Active" icon={Lock} tone="success" hint="In transit & at rest" />
        <StatCard label="Data categories tracked" value={inventory.length} icon={Database} />
        <StatCard label="Open privacy requests" value={0} icon={UserCheck} tone="success" />
      </div>

      {/* Controls */}
      <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {controls.map((c) => (
          <Card key={c.title}>
            <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-accent text-primary">
              <c.icon className="h-4 w-4" />
            </span>
            <h3 className="mt-3 text-sm font-semibold">{c.title}</h3>
            <p className="mt-1 text-xs text-muted-foreground">{c.desc}</p>
          </Card>
        ))}
      </div>

      {/* Inventory */}
      <Card className="mt-6">
        <h3 className="font-semibold">Data inventory & classification</h3>
        <p className="mt-1 text-xs text-muted-foreground">Everything Chai stores, where it came from, and how long it's kept.</p>
        <div className="mt-4 overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border text-left text-xs text-muted-foreground">
                <th className="py-2 pr-4 font-medium">Data type</th>
                <th className="py-2 pr-4 font-medium">Source</th>
                <th className="py-2 pr-4 font-medium">Classification</th>
                <th className="py-2 font-medium">Retention</th>
              </tr>
            </thead>
            <tbody>
              {inventory.map((d) => (
                <tr key={d.type} className="border-b border-border/60 last:border-0">
                  <td className="py-2.5 pr-4 font-medium">{d.type}</td>
                  <td className="py-2.5 pr-4 text-muted-foreground">{d.source}</td>
                  <td className="py-2.5 pr-4">
                    <span className="rounded-full bg-secondary px-2 py-0.5 text-xs text-secondary-foreground">{d.classification}</span>
                  </td>
                  <td className="py-2.5 text-muted-foreground">{d.retention}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      <div className="mt-6 grid gap-6 lg:grid-cols-2">
        {/* Audit log */}
        <Card>
          <h3 className="font-semibold">Audit log</h3>
          <p className="mt-1 text-xs text-muted-foreground">A record of every access and change.</p>
          <ul className="mt-4 space-y-3">
            {auditLog.map((a, i) => (
              <li key={i} className="flex items-start gap-3 text-sm">
                <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                <div>
                  <p>{a.action}</p>
                  <p className="text-xs text-muted-foreground">{a.who} · {a.when}</p>
                </div>
              </li>
            ))}
          </ul>
        </Card>

        {/* Requests + reports */}
        <Card>
          <h3 className="font-semibold">Privacy requests & reports</h3>
          <p className="mt-1 text-xs text-muted-foreground">Handle data subject requests and download compliance documents.</p>
          <div className="mt-4 grid grid-cols-2 gap-2">
            <button
              onClick={() => toast.success("Data export requested", { description: "We'll prepare a full export of stored data." })}
              className="inline-flex items-center justify-center gap-1.5 rounded-lg border border-border py-2.5 text-sm font-medium hover:bg-accent"
            >
              <Download className="h-4 w-4" /> Export data
            </button>
            <button
              onClick={() => toast.success("Erasure request logged", { description: "Right-to-be-forgotten request recorded." })}
              className="inline-flex items-center justify-center gap-1.5 rounded-lg border border-border py-2.5 text-sm font-medium hover:bg-accent"
            >
              <Trash2 className="h-4 w-4" /> Forget a customer
            </button>
          </div>
          <div className="mt-4 space-y-2">
            {reports.map((r) => (
              <button
                key={r.name}
                onClick={() => toast.success(`${r.name} generated`, { description: "Download ready (demo)." })}
                className="flex w-full items-center justify-between rounded-lg bg-secondary/50 px-3 py-2.5 text-sm transition-colors hover:bg-secondary"
              >
                <span className="flex items-center gap-2">
                  <r.icon className="h-4 w-4 text-muted-foreground" />
                  {r.name}
                </span>
                <Download className="h-4 w-4 text-muted-foreground" />
              </button>
            ))}
          </div>
        </Card>
      </div>
    </div>
  );
}
