/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppTrustRouteImport } from './routes/_authenticated.app.trust'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated.app.settings'
import { Route as AuthenticatedAppPlannerRouteImport } from './routes/_authenticated.app.planner'
import { Route as AuthenticatedAppInsightsRouteImport } from './routes/_authenticated.app.insights'
import { Route as AuthenticatedAppDataQualityRouteImport } from './routes/_authenticated.app.data-quality'
import { Route as AuthenticatedAppDataRouteImport } from './routes/_authenticated.app.data'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated.app.dashboard'
import { Route as AuthenticatedAppCustomersRouteImport } from './routes/_authenticated.app.customers'
import { Route as AuthenticatedAppChurnedRouteImport } from './routes/_authenticated.app.churned'
import { Route as AuthenticatedAppCustomersIndexRouteImport } from './routes/_authenticated.app.customers.index'
import { Route as ApiPublicAccountingCallbackRouteImport } from './routes/api/public/accounting.callback'
import { Route as AuthenticatedAppCustomersIdRouteImport } from './routes/_authenticated.app.customers.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTrustRoute = AuthenticatedAppTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPlannerRoute = AuthenticatedAppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppInsightsRoute =
  AuthenticatedAppInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDataQualityRoute =
  AuthenticatedAppDataQualityRouteImport.update({
    id: '/data-quality',
    path: '/data-quality',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDataRoute = AuthenticatedAppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCustomersRoute =
  AuthenticatedAppCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChurnedRoute = AuthenticatedAppChurnedRouteImport.update({
  id: '/churned',
  path: '/churned',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCustomersIndexRoute =
  AuthenticatedAppCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppCustomersRoute,
  } as any)
const ApiPublicAccountingCallbackRoute =
  ApiPublicAccountingCallbackRouteImport.update({
    id: '/api/public/accounting/callback',
    path: '/api/public/accounting/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppCustomersIdRoute =
  AuthenticatedAppCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/churned': typeof AuthenticatedAppChurnedRoute
  '/app/customers': typeof AuthenticatedAppCustomersRouteWithChildren
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/data': typeof AuthenticatedAppDataRoute
  '/app/data-quality': typeof AuthenticatedAppDataQualityRoute
  '/app/insights': typeof AuthenticatedAppInsightsRoute
  '/app/planner': typeof AuthenticatedAppPlannerRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/trust': typeof AuthenticatedAppTrustRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/customers/$id': typeof AuthenticatedAppCustomersIdRoute
  '/api/public/accounting/callback': typeof ApiPublicAccountingCallbackRoute
  '/app/customers/': typeof AuthenticatedAppCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/churned': typeof AuthenticatedAppChurnedRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/data': typeof AuthenticatedAppDataRoute
  '/app/data-quality': typeof AuthenticatedAppDataQualityRoute
  '/app/insights': typeof AuthenticatedAppInsightsRoute
  '/app/planner': typeof AuthenticatedAppPlannerRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/trust': typeof AuthenticatedAppTrustRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/customers/$id': typeof AuthenticatedAppCustomersIdRoute
  '/api/public/accounting/callback': typeof ApiPublicAccountingCallbackRoute
  '/app/customers': typeof AuthenticatedAppCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/app/churned': typeof AuthenticatedAppChurnedRoute
  '/_authenticated/app/customers': typeof AuthenticatedAppCustomersRouteWithChildren
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/data': typeof AuthenticatedAppDataRoute
  '/_authenticated/app/data-quality': typeof AuthenticatedAppDataQualityRoute
  '/_authenticated/app/insights': typeof AuthenticatedAppInsightsRoute
  '/_authenticated/app/planner': typeof AuthenticatedAppPlannerRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/trust': typeof AuthenticatedAppTrustRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/customers/$id': typeof AuthenticatedAppCustomersIdRoute
  '/api/public/accounting/callback': typeof ApiPublicAccountingCallbackRoute
  '/_authenticated/app/customers/': typeof AuthenticatedAppCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/app/churned'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/data'
    | '/app/data-quality'
    | '/app/insights'
    | '/app/planner'
    | '/app/settings'
    | '/app/trust'
    | '/app/'
    | '/app/customers/$id'
    | '/api/public/accounting/callback'
    | '/app/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/onboarding'
    | '/app/churned'
    | '/app/dashboard'
    | '/app/data'
    | '/app/data-quality'
    | '/app/insights'
    | '/app/planner'
    | '/app/settings'
    | '/app/trust'
    | '/app'
    | '/app/customers/$id'
    | '/api/public/accounting/callback'
    | '/app/customers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/app/churned'
    | '/_authenticated/app/customers'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/data'
    | '/_authenticated/app/data-quality'
    | '/_authenticated/app/insights'
    | '/_authenticated/app/planner'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/trust'
    | '/_authenticated/app/'
    | '/_authenticated/app/customers/$id'
    | '/api/public/accounting/callback'
    | '/_authenticated/app/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicAccountingCallbackRoute: typeof ApiPublicAccountingCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/trust': {
      id: '/_authenticated/app/trust'
      path: '/trust'
      fullPath: '/app/trust'
      preLoaderRoute: typeof AuthenticatedAppTrustRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/planner': {
      id: '/_authenticated/app/planner'
      path: '/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AuthenticatedAppPlannerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/insights': {
      id: '/_authenticated/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AuthenticatedAppInsightsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/data-quality': {
      id: '/_authenticated/app/data-quality'
      path: '/data-quality'
      fullPath: '/app/data-quality'
      preLoaderRoute: typeof AuthenticatedAppDataQualityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/data': {
      id: '/_authenticated/app/data'
      path: '/data'
      fullPath: '/app/data'
      preLoaderRoute: typeof AuthenticatedAppDataRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/customers': {
      id: '/_authenticated/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AuthenticatedAppCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/churned': {
      id: '/_authenticated/app/churned'
      path: '/churned'
      fullPath: '/app/churned'
      preLoaderRoute: typeof AuthenticatedAppChurnedRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/customers/': {
      id: '/_authenticated/app/customers/'
      path: '/'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AuthenticatedAppCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedAppCustomersRoute
    }
    '/api/public/accounting/callback': {
      id: '/api/public/accounting/callback'
      path: '/api/public/accounting/callback'
      fullPath: '/api/public/accounting/callback'
      preLoaderRoute: typeof ApiPublicAccountingCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/customers/$id': {
      id: '/_authenticated/app/customers/$id'
      path: '/$id'
      fullPath: '/app/customers/$id'
      preLoaderRoute: typeof AuthenticatedAppCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAppCustomersRoute
    }
  }
}

interface AuthenticatedAppCustomersRouteChildren {
  AuthenticatedAppCustomersIdRoute: typeof AuthenticatedAppCustomersIdRoute
  AuthenticatedAppCustomersIndexRoute: typeof AuthenticatedAppCustomersIndexRoute
}

const AuthenticatedAppCustomersRouteChildren: AuthenticatedAppCustomersRouteChildren =
  {
    AuthenticatedAppCustomersIdRoute: AuthenticatedAppCustomersIdRoute,
    AuthenticatedAppCustomersIndexRoute: AuthenticatedAppCustomersIndexRoute,
  }

const AuthenticatedAppCustomersRouteWithChildren =
  AuthenticatedAppCustomersRoute._addFileChildren(
    AuthenticatedAppCustomersRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppChurnedRoute: typeof AuthenticatedAppChurnedRoute
  AuthenticatedAppCustomersRoute: typeof AuthenticatedAppCustomersRouteWithChildren
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppDataRoute: typeof AuthenticatedAppDataRoute
  AuthenticatedAppDataQualityRoute: typeof AuthenticatedAppDataQualityRoute
  AuthenticatedAppInsightsRoute: typeof AuthenticatedAppInsightsRoute
  AuthenticatedAppPlannerRoute: typeof AuthenticatedAppPlannerRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTrustRoute: typeof AuthenticatedAppTrustRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppChurnedRoute: AuthenticatedAppChurnedRoute,
  AuthenticatedAppCustomersRoute: AuthenticatedAppCustomersRouteWithChildren,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppDataRoute: AuthenticatedAppDataRoute,
  AuthenticatedAppDataQualityRoute: AuthenticatedAppDataQualityRoute,
  AuthenticatedAppInsightsRoute: AuthenticatedAppInsightsRoute,
  AuthenticatedAppPlannerRoute: AuthenticatedAppPlannerRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTrustRoute: AuthenticatedAppTrustRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicAccountingCallbackRoute: ApiPublicAccountingCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
