/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppChurnedRouteImport } from './routes/_authenticated.app.churned'
import { Route as AuthenticatedAppCustomersRouteImport } from './routes/_authenticated.app.customers'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated.app.dashboard'
import { Route as AuthenticatedAppDataRouteImport } from './routes/_authenticated.app.data'
import { Route as AuthenticatedAppDataQualityRouteImport } from './routes/_authenticated.app.data-quality'
import { Route as AuthenticatedAppIdentityRouteImport } from './routes/_authenticated.app.identity'
import { Route as AuthenticatedAppInsightsRouteImport } from './routes/_authenticated.app.insights'
import { Route as AuthenticatedAppPlannerRouteImport } from './routes/_authenticated.app.planner'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated.app.settings'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated.app.team'
import { Route as AuthenticatedAppTodayRouteImport } from './routes/_authenticated.app.today'
import { Route as AuthenticatedAppWelcomeRouteImport } from './routes/_authenticated.app.welcome'
import { Route as AuthenticatedAppCustomersIndexRouteImport } from './routes/_authenticated.app.customers.index'
import { Route as AuthenticatedAppCustomersIdRouteImport } from './routes/_authenticated.app.customers.$id'
import { Route as ApiPublicAccountingCallbackRouteImport } from './routes/api/public/accounting.callback'
import { Route as ApiPublicHooksDailyScoreRouteImport } from './routes/api/public/hooks/daily-score'
import { Route as ApiPublicHooksDailySyncRouteImport } from './routes/api/public/hooks/daily-sync'
import { Route as ApiPublicIntercomCallbackRouteImport } from './routes/api/public/intercom.callback'
import { Route as ApiPublicZendeskCallbackRouteImport } from './routes/api/public/zendesk.callback'
import { Route as ApiPublicZohoCallbackRouteImport } from './routes/api/public/zoho.callback'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChurnedRoute = AuthenticatedAppChurnedRouteImport.update({
  id: '/churned',
  path: '/churned',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCustomersRoute =
  AuthenticatedAppCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDataRoute = AuthenticatedAppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDataQualityRoute =
  AuthenticatedAppDataQualityRouteImport.update({
    id: '/data-quality',
    path: '/data-quality',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppIdentityRoute =
  AuthenticatedAppIdentityRouteImport.update({
    id: '/identity',
    path: '/identity',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInsightsRoute =
  AuthenticatedAppInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPlannerRoute = AuthenticatedAppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTodayRoute = AuthenticatedAppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWelcomeRoute = AuthenticatedAppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCustomersIndexRoute =
  AuthenticatedAppCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppCustomersRoute,
  } as any)
const AuthenticatedAppCustomersIdRoute =
  AuthenticatedAppCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppCustomersRoute,
  } as any)
const ApiPublicAccountingCallbackRoute =
  ApiPublicAccountingCallbackRouteImport.update({
    id: '/api/public/accounting/callback',
    path: '/api/public/accounting/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyScoreRoute =
  ApiPublicHooksDailyScoreRouteImport.update({
    id: '/api/public/hooks/daily-score',
    path: '/api/public/hooks/daily-score',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailySyncRoute = ApiPublicHooksDailySyncRouteImport.update({
  id: '/api/public/hooks/daily-sync',
  path: '/api/public/hooks/daily-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntercomCallbackRoute =
  ApiPublicIntercomCallbackRouteImport.update({
    id: '/api/public/intercom/callback',
    path: '/api/public/intercom/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicZendeskCallbackRoute =
  ApiPublicZendeskCallbackRouteImport.update({
    id: '/api/public/zendesk/callback',
    path: '/api/public/zendesk/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicZohoCallbackRoute = ApiPublicZohoCallbackRouteImport.update({
  id: '/api/public/zoho/callback',
  path: '/api/public/zoho/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/churned': typeof AuthenticatedAppChurnedRoute
  '/app/customers': typeof AuthenticatedAppCustomersRouteWithChildren
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/data': typeof AuthenticatedAppDataRoute
  '/app/data-quality': typeof AuthenticatedAppDataQualityRoute
  '/app/identity': typeof AuthenticatedAppIdentityRoute
  '/app/insights': typeof AuthenticatedAppInsightsRoute
  '/app/planner': typeof AuthenticatedAppPlannerRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/today': typeof AuthenticatedAppTodayRoute
  '/app/welcome': typeof AuthenticatedAppWelcomeRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/customers/$id': typeof AuthenticatedAppCustomersIdRoute
  '/api/public/accounting/callback': typeof ApiPublicAccountingCallbackRoute
  '/api/public/hooks/daily-score': typeof ApiPublicHooksDailyScoreRoute
  '/api/public/hooks/daily-sync': typeof ApiPublicHooksDailySyncRoute
  '/api/public/intercom/callback': typeof ApiPublicIntercomCallbackRoute
  '/api/public/zendesk/callback': typeof ApiPublicZendeskCallbackRoute
  '/api/public/zoho/callback': typeof ApiPublicZohoCallbackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/customers/': typeof AuthenticatedAppCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/churned': typeof AuthenticatedAppChurnedRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/data': typeof AuthenticatedAppDataRoute
  '/app/data-quality': typeof AuthenticatedAppDataQualityRoute
  '/app/identity': typeof AuthenticatedAppIdentityRoute
  '/app/insights': typeof AuthenticatedAppInsightsRoute
  '/app/planner': typeof AuthenticatedAppPlannerRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/today': typeof AuthenticatedAppTodayRoute
  '/app/welcome': typeof AuthenticatedAppWelcomeRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/customers/$id': typeof AuthenticatedAppCustomersIdRoute
  '/api/public/accounting/callback': typeof ApiPublicAccountingCallbackRoute
  '/api/public/hooks/daily-score': typeof ApiPublicHooksDailyScoreRoute
  '/api/public/hooks/daily-sync': typeof ApiPublicHooksDailySyncRoute
  '/api/public/intercom/callback': typeof ApiPublicIntercomCallbackRoute
  '/api/public/zendesk/callback': typeof ApiPublicZendeskCallbackRoute
  '/api/public/zoho/callback': typeof ApiPublicZohoCallbackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/customers': typeof AuthenticatedAppCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/app/churned': typeof AuthenticatedAppChurnedRoute
  '/_authenticated/app/customers': typeof AuthenticatedAppCustomersRouteWithChildren
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/data': typeof AuthenticatedAppDataRoute
  '/_authenticated/app/data-quality': typeof AuthenticatedAppDataQualityRoute
  '/_authenticated/app/identity': typeof AuthenticatedAppIdentityRoute
  '/_authenticated/app/insights': typeof AuthenticatedAppInsightsRoute
  '/_authenticated/app/planner': typeof AuthenticatedAppPlannerRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/today': typeof AuthenticatedAppTodayRoute
  '/_authenticated/app/welcome': typeof AuthenticatedAppWelcomeRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/customers/$id': typeof AuthenticatedAppCustomersIdRoute
  '/api/public/accounting/callback': typeof ApiPublicAccountingCallbackRoute
  '/api/public/hooks/daily-score': typeof ApiPublicHooksDailyScoreRoute
  '/api/public/hooks/daily-sync': typeof ApiPublicHooksDailySyncRoute
  '/api/public/intercom/callback': typeof ApiPublicIntercomCallbackRoute
  '/api/public/zendesk/callback': typeof ApiPublicZendeskCallbackRoute
  '/api/public/zoho/callback': typeof ApiPublicZohoCallbackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/app/customers/': typeof AuthenticatedAppCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/invite/$token'
    | '/app/churned'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/data'
    | '/app/data-quality'
    | '/app/identity'
    | '/app/insights'
    | '/app/planner'
    | '/app/settings'
    | '/app/team'
    | '/app/today'
    | '/app/welcome'
    | '/app/'
    | '/app/customers/$id'
    | '/api/public/accounting/callback'
    | '/api/public/hooks/daily-score'
    | '/api/public/hooks/daily-sync'
    | '/api/public/intercom/callback'
    | '/api/public/zendesk/callback'
    | '/api/public/zoho/callback'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/app/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/onboarding'
    | '/invite/$token'
    | '/app/churned'
    | '/app/dashboard'
    | '/app/data'
    | '/app/data-quality'
    | '/app/identity'
    | '/app/insights'
    | '/app/planner'
    | '/app/settings'
    | '/app/team'
    | '/app/today'
    | '/app/welcome'
    | '/app'
    | '/app/customers/$id'
    | '/api/public/accounting/callback'
    | '/api/public/hooks/daily-score'
    | '/api/public/hooks/daily-sync'
    | '/api/public/intercom/callback'
    | '/api/public/zendesk/callback'
    | '/api/public/zoho/callback'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/app/customers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/invite/$token'
    | '/_authenticated/app/churned'
    | '/_authenticated/app/customers'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/data'
    | '/_authenticated/app/data-quality'
    | '/_authenticated/app/identity'
    | '/_authenticated/app/insights'
    | '/_authenticated/app/planner'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/team'
    | '/_authenticated/app/today'
    | '/_authenticated/app/welcome'
    | '/_authenticated/app/'
    | '/_authenticated/app/customers/$id'
    | '/api/public/accounting/callback'
    | '/api/public/hooks/daily-score'
    | '/api/public/hooks/daily-sync'
    | '/api/public/intercom/callback'
    | '/api/public/zendesk/callback'
    | '/api/public/zoho/callback'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/app/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicAccountingCallbackRoute: typeof ApiPublicAccountingCallbackRoute
  ApiPublicHooksDailyScoreRoute: typeof ApiPublicHooksDailyScoreRoute
  ApiPublicHooksDailySyncRoute: typeof ApiPublicHooksDailySyncRoute
  ApiPublicIntercomCallbackRoute: typeof ApiPublicIntercomCallbackRoute
  ApiPublicZendeskCallbackRoute: typeof ApiPublicZendeskCallbackRoute
  ApiPublicZohoCallbackRoute: typeof ApiPublicZohoCallbackRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/churned': {
      id: '/_authenticated/app/churned'
      path: '/churned'
      fullPath: '/app/churned'
      preLoaderRoute: typeof AuthenticatedAppChurnedRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/customers': {
      id: '/_authenticated/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AuthenticatedAppCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/data': {
      id: '/_authenticated/app/data'
      path: '/data'
      fullPath: '/app/data'
      preLoaderRoute: typeof AuthenticatedAppDataRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/data-quality': {
      id: '/_authenticated/app/data-quality'
      path: '/data-quality'
      fullPath: '/app/data-quality'
      preLoaderRoute: typeof AuthenticatedAppDataQualityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/identity': {
      id: '/_authenticated/app/identity'
      path: '/identity'
      fullPath: '/app/identity'
      preLoaderRoute: typeof AuthenticatedAppIdentityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/insights': {
      id: '/_authenticated/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AuthenticatedAppInsightsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/planner': {
      id: '/_authenticated/app/planner'
      path: '/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AuthenticatedAppPlannerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/today': {
      id: '/_authenticated/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AuthenticatedAppTodayRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/welcome': {
      id: '/_authenticated/app/welcome'
      path: '/welcome'
      fullPath: '/app/welcome'
      preLoaderRoute: typeof AuthenticatedAppWelcomeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/customers/': {
      id: '/_authenticated/app/customers/'
      path: '/'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AuthenticatedAppCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedAppCustomersRoute
    }
    '/_authenticated/app/customers/$id': {
      id: '/_authenticated/app/customers/$id'
      path: '/$id'
      fullPath: '/app/customers/$id'
      preLoaderRoute: typeof AuthenticatedAppCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAppCustomersRoute
    }
    '/api/public/accounting/callback': {
      id: '/api/public/accounting/callback'
      path: '/api/public/accounting/callback'
      fullPath: '/api/public/accounting/callback'
      preLoaderRoute: typeof ApiPublicAccountingCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-score': {
      id: '/api/public/hooks/daily-score'
      path: '/api/public/hooks/daily-score'
      fullPath: '/api/public/hooks/daily-score'
      preLoaderRoute: typeof ApiPublicHooksDailyScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-sync': {
      id: '/api/public/hooks/daily-sync'
      path: '/api/public/hooks/daily-sync'
      fullPath: '/api/public/hooks/daily-sync'
      preLoaderRoute: typeof ApiPublicHooksDailySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/intercom/callback': {
      id: '/api/public/intercom/callback'
      path: '/api/public/intercom/callback'
      fullPath: '/api/public/intercom/callback'
      preLoaderRoute: typeof ApiPublicIntercomCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zendesk/callback': {
      id: '/api/public/zendesk/callback'
      path: '/api/public/zendesk/callback'
      fullPath: '/api/public/zendesk/callback'
      preLoaderRoute: typeof ApiPublicZendeskCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zoho/callback': {
      id: '/api/public/zoho/callback'
      path: '/api/public/zoho/callback'
      fullPath: '/api/public/zoho/callback'
      preLoaderRoute: typeof ApiPublicZohoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppCustomersRouteChildren {
  AuthenticatedAppCustomersIdRoute: typeof AuthenticatedAppCustomersIdRoute
  AuthenticatedAppCustomersIndexRoute: typeof AuthenticatedAppCustomersIndexRoute
}

const AuthenticatedAppCustomersRouteChildren: AuthenticatedAppCustomersRouteChildren =
  {
    AuthenticatedAppCustomersIdRoute: AuthenticatedAppCustomersIdRoute,
    AuthenticatedAppCustomersIndexRoute: AuthenticatedAppCustomersIndexRoute,
  }

const AuthenticatedAppCustomersRouteWithChildren =
  AuthenticatedAppCustomersRoute._addFileChildren(
    AuthenticatedAppCustomersRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppChurnedRoute: typeof AuthenticatedAppChurnedRoute
  AuthenticatedAppCustomersRoute: typeof AuthenticatedAppCustomersRouteWithChildren
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppDataRoute: typeof AuthenticatedAppDataRoute
  AuthenticatedAppDataQualityRoute: typeof AuthenticatedAppDataQualityRoute
  AuthenticatedAppIdentityRoute: typeof AuthenticatedAppIdentityRoute
  AuthenticatedAppInsightsRoute: typeof AuthenticatedAppInsightsRoute
  AuthenticatedAppPlannerRoute: typeof AuthenticatedAppPlannerRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppTodayRoute: typeof AuthenticatedAppTodayRoute
  AuthenticatedAppWelcomeRoute: typeof AuthenticatedAppWelcomeRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppChurnedRoute: AuthenticatedAppChurnedRoute,
  AuthenticatedAppCustomersRoute: AuthenticatedAppCustomersRouteWithChildren,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppDataRoute: AuthenticatedAppDataRoute,
  AuthenticatedAppDataQualityRoute: AuthenticatedAppDataQualityRoute,
  AuthenticatedAppIdentityRoute: AuthenticatedAppIdentityRoute,
  AuthenticatedAppInsightsRoute: AuthenticatedAppInsightsRoute,
  AuthenticatedAppPlannerRoute: AuthenticatedAppPlannerRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppTodayRoute: AuthenticatedAppTodayRoute,
  AuthenticatedAppWelcomeRoute: AuthenticatedAppWelcomeRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicAccountingCallbackRoute: ApiPublicAccountingCallbackRoute,
  ApiPublicHooksDailyScoreRoute: ApiPublicHooksDailyScoreRoute,
  ApiPublicHooksDailySyncRoute: ApiPublicHooksDailySyncRoute,
  ApiPublicIntercomCallbackRoute: ApiPublicIntercomCallbackRoute,
  ApiPublicZendeskCallbackRoute: ApiPublicZendeskCallbackRoute,
  ApiPublicZohoCallbackRoute: ApiPublicZohoCallbackRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
