ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS size text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS customers text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS avg_value text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS what_buy text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cadence text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS lifespan text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS concerns text NOT NULL DEFAULT '';