// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import { inspectServerEnvAsync } from "@/lib/server-env";
import type { Database } from "./types";

async function createSupabaseAdminClient() {
  const [urlLookup, keyLookup] = await Promise.all([
    inspectServerEnvAsync("SUPABASE_URL"),
    inspectServerEnvAsync("SUPABASE_SERVICE_ROLE_KEY"),
  ]);
  const SUPABASE_URL = urlLookup.value;
  const SUPABASE_SERVICE_ROLE_KEY = keyLookup.value;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ["SUPABASE_SERVICE_ROLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const supabaseAdmin = await getSupabaseAdmin();
// A fresh client is created per call so Worker bindings are read after request initialisation.
export async function getSupabaseAdmin() {
  return createSupabaseAdminClient();
}
