// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caujcnyrmpakrkjiffet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhdWpjbnlybXBha3JramlmZmV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgxNTQ1NjYsImV4cCI6MjEwMzczMDU2Nn0.Lgf4oLlLsY0x2pV38DaZur3FKAJ6etkTxH2fh4-iKh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});