// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { inspectServerEnvAsync } from '@/lib/server-env';

async function createSupabaseAdminClient() {
  // Credentials are read through the multi-source async server-env lookup (the
  // same method the AI provider uses) rather than process.env alone: on the
  // published site the app runs as a Cloudflare Worker where secrets arrive as
  // worker bindings, not process env vars.
  const urlLookup = await inspectServerEnvAsync('SUPABASE_URL');
  const keyLookup = await inspectServerEnvAsync('SUPABASE_SERVICE_ROLE_KEY');

  const SUPABASE_URL = urlLookup.value;
  const SUPABASE_SERVICE_ROLE_KEY = keyLookup.value;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: Awaited<ReturnType<typeof createSupabaseAdminClient>> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const supabaseAdmin = await getSupabaseAdmin();
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export async function getSupabaseAdmin() {
  if (!_supabaseAdmin) _supabaseAdmin = await createSupabaseAdminClient();
  return _supabaseAdmin;
}

export const supabaseAdmin = new Proxy({} as Awaited<ReturnType<typeof createSupabaseAdminClient>>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) {
      throw new Error(
        "supabaseAdmin accessed before initialisation — await getSupabaseAdmin() first",
      );
    }
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
